# ????
spring:
  application:
    name: demo-application

  # ?????
  datasource:
    url: jdbc:mysql://localhost:3306/database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# ?????
server:
  port: 8080
  servlet:
    context-path: /api

# ????
logging:
  level:
    root: INFO
    com.example: DEBUG
  file:
    name: logs/application.log